service:
  name: webhook-interceptor

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs8.10
  stackTags:
    owner: "communication-ecosystem"
    service: "webhook-interceptor"

  # load self:custom.environment into process.env
  environment:
    googClientId: ${self:custom.environment.googClientId}
    googClientSecret: ${self:custom.environment.googClientSecret}


# load env.yml into self:custom.environment
custom:
  environment: ${file(env.yml):default}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  signinPage:
    handler: handler.signinPage
    events:
      - http:
          method: get
          path: signin
  tokenSignin:
    handler: handler.tokenSignin
    events:
      - http:
          path: tokenSignin
          method: post
          cors: true